add_newline = true
[character]
success_symbol = "[❯](bold #f72585)[❯](bold #4cc9f0)"
error_symbol = "[✖](bold red)"
[directory]
style = "bold #4cc9f0"
format = "in [$path]($style) "
[nodejs]
symbol = "󰎙 "
style = "bold #4361ee"
disabled = false
