add_newline = true
[character]
success_symbol = "[λ](bold purple)"
error_symbol = "[λ](bold red)"
[directory]
style = "bold blue"
truncation_length = 3
[nodejs]
symbol = " "
style = "bold green"
disabled = false
